name: SharedVersion
on:
  push:
    branches:
      - master
    paths:
      - "packages/libs/shared/**/*.js"
      - "packages/libs/shared/**/*.ts"

jobs:
  release:
    name: Release
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: echo "Esto solo corre si hay un cambio en el SHARED :D"
